import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/shared/navbar";
import { inter } from "@/lib/font";
import ModernFooter from "@/components/footer/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans antialiased`}>
        <Header />
        {children}
        <ModernFooter />
      </body>
    </html>
  );
}
