/* eslint-disable */
import { Product } from "@/interface/product";
export const productsData: Product[] = [
  {
    id: "1",
    productId: "p1",
    name: "100 Percent Apple Juice",
    description: "64 fl oz bottle",
    brand: "Great Value",
    images: ["/Editorspick/appleJuice.png"],
    price: 0.5,
    mrp: 1.99,
    status: "Live",
    material: "Glass Bottle",
    warrantyPeriod: "No Warranty",
    warrantyType: "Fresh Product",
    countryOfOrigin: "USA",
    categories: ["Juice", "Beverages", "Groceries"],
    variants: [],
    featuredTags: [{ feature: { name: "Organic" } }],
  },
  {
    id: "2",
    productId: "p2",
    name: "Rising Crust Frozen Pizza, Supreme",
    brand: "Great Value",
    description: "Frozen, Ready-to-bake Pizza",
    images: ["/Editorspick/crustpizza.png"],
    price: 8.89,
    mrp: 9.88,
    status: "Live",
    material: "Box",
    warrantyPeriod: "3 Days",
    warrantyType: "Frozen Goods",
    countryOfOrigin: "USA",
    categories: ["Pizza", "Frozen Foods"],
    variants: [
      {
        size: "Medium",
        id: "v1",
        productId: "p2",
        colors: ["Red"],
        inventory: 10,
      },
      {
        size: "Large",
        id: "v2",
        productId: "p2",
        colors: ["Red"],
        inventory: 5,
      },
    ],

    // featuredTags: [{ feature: { name: "Best Seller" } }],
  },
  {
    id: "3",
    productId: "p3",
    name: "California Thin Crust Pizza",
    brand: "California Pizza Kitchen",
    description: "Crispy Thin Crust with premium toppings",
    images: ["/Editorspick/pizza.png"],
    price: 11.77,
    mrp: 15.77,
    status: "Live",
    material: "Box",
    warrantyPeriod: "3 Days",
    warrantyType: "Frozen Goods",
    countryOfOrigin: "USA",
    categories: ["Pizza", "Dinner", "Frozen"],
    variants: [
      {
        size: "Regular",
        id: "v3",
        productId: "p3",
        colors: ["Yellow"],
        inventory: 8,
      },
    ],
    featuredTags: [{ feature: { name: "Thin Crust" } }],
  },
  {
    id: "4",
    productId: "p4",
    name: "Cantaloupe Melon Fresh Organic Cut",
    brand: "Fresh Farm",
    description: "Fresh cut melon pack",
    images: ["/Editorspick/melon.png"],
    price: 1.25,
    mrp: 2.89,
    status: "Live",
    material: "Plastic Tray",
    warrantyPeriod: "2 Days",
    warrantyType: "Perishable",
    countryOfOrigin: "Mexico",
    categories: ["Fruits", "Organic"],
    variants: [],
    featuredTags: [{ feature: { name: "Organic" } }],
  },
  {
    id: "5",
    productId: "p5",
    name: "Simply Orange Pulp Free Juice",
    brand: "Simply",
    description: "52 fl oz bottle",
    images: ["/Editorspick/orangepulp.png"],
    price: 2.45,
    mrp: 4.13,
    status: "Live",
    material: "Plastic Bottle",
    warrantyPeriod: "7 Days",
    warrantyType: "Refrigerated",
    countryOfOrigin: "USA",
    categories: ["Juice", "Citrus"],
    variants: [],
    featuredTags: [],
  },
  {
    id: "6",
    productId: "p6",
    name: "Angel Soft Toilet Paper, 9 Mega Rolls",
    brand: "Angel Soft",
    description: "9 Mega Rolls Pack",
    images: ["/Editorspick/toiletpaper.png"],
    price: 14.12,
    mrp: 17.32,
    status: "Live",
    material: "Paper",
    warrantyPeriod: "N/A",
    warrantyType: "Hygiene Product",
    countryOfOrigin: "USA",
    categories: ["Toiletries", "Home Essentials"],
    variants: [],
    featuredTags: [{ feature: { name: "Mega Rolls" } }],
  },
  {
    id: "7",
    productId: "p7",
    name: "Organic Avocados (3 Pack)",
    brand: "GreenWorld",
    description: "Fresh organic avocados",
    images: ["/Editorspick/pepperoniPizza.png"],
    price: 3.99,
    mrp: 5.49,
    status: "Live",
    material: "Net Bag",
    warrantyPeriod: "5 Days",
    warrantyType: "Produce",
    countryOfOrigin: "Mexico",
    categories: ["Fruits", "Organic"],
    variants: [],
    featuredTags: [{ feature: { name: "Organic" } }],
  },
  {
    id: "8",
    productId: "p8",
    name: "Premium Ground Coffee",
    brand: "Morning Brew",
    description: "Finely roasted Arabica beans",
    images: ["/Editorspick/strawberries.png"],
    price: 6.45,
    mrp: 8.99,
    status: "Disabled",
    material: "Pouch",
    warrantyPeriod: "6 Months",
    warrantyType: "Dry Goods",
    countryOfOrigin: "Colombia",
    categories: ["Coffee", "Pantry", "Beverages"],
    variants: [
      {
        size: "250g",
        id: "v3",
        productId: "p3",
        colors: ["Green"],
        inventory: 8,
      },
    ],
    featuredTags: [{ feature: { name: "Arabica" } }],
  },
];
