export const colorsColumn1 = [
  "Aquamarine",
  "Violet",
  "Purple",
  "Crimson",
  "Indigo",
  "Blue",
  "Mauv",
  "Fuscia",
  "Puce",
  "Green",
  "Goldenrod",
  "Turquoise",
  "Khaki",
  "Teal",
  "Red",
  "Yellow",
  "Orange",
  "Pink",
  "Navy",
  "Olive",
  "Beige",
  "Maroon",
  "Magenta",
  "Brown",
  // "Cyan",
  // "Teal",
  // "Lime",
  // "Indigo",
  // "Violet",
  // "Turquoise",
  // "Tan",
  // "Aquamarine",
  // "Goldenrod",
];

export const colorBackgroundMap = {
  Aquamarine: "#7FFFD4",
  Violet: "#EE82EE",
  Purple: "#800080",
  Crimson: "#DC143C",
  Indigo: "#4B0082",
  Blue: "#0000FF",
  Mauv: "#E0B0FF",
  Fuscia: "#FF00FF",
  Pink: "#FFC0CB",
  Puce: "#CC8899",
  Maroon: "#800000",
  Green: "#008000",
  Goldenrod: "#DAA520",
  Turquoise: "#40E0D0",
  Khaki: "#F0E68C",
  Teal: "#008080",
  Red: "#FF0000",
  Yellow: "#FFFF00",
  Orange: "#FFA500",
  Magenta: "#FF00FF",
  Brown: "#A52A2A",
  Navy: "#000080",
  Olive: "#808000",
  Beige: "#F5F5DC",
};
